### PR TITLE
Enhanced project section layout

### LINKED ISSUE #9: Project layout
In the project section of HTML currently, the table tag is used for layout the various projects. So use divs and nested divs instead of table tag and use proper layout styling (either CSS flexbox or CSS grid) to layout them properly.

For reference regarding grid: https://css-tricks.com/snippets/css/complete-guide-grid/

table

### PR DESCRIPTION
**Pull request by vaibhav-sharma-frontend**
Improved the layout of the project section using CSS grid and remove the old table layout method.
Issue Fixed: #9

### CODE REVIEW

**Comment by vaibhav-sharma-frontend** [comment]
Screenshot
Annotation 2019-12-08 183756

@0xPrateek review it

**Comment by 0xPrateek** [comment]
PR :+1:  
Make sure to replace the new image of the project layout in readme.md

**Comment by vaibhav-sharma-frontend** [comment]
> PR 👍
> Make sure to replace the new image of the project layout in readme.md

but u have hosted that previous image on some URL so can u host this image too and make the necessary adjustment

Annotation 2019-12-08 185105

**Comment by 0xPrateek** [comment]
@vsharma20v  okay..!
Your work is amazing.
Have a look at other issues as well.

**Comment by vaibhav-sharma-frontend** [comment]
@0xPrateek I will surely take some other issues after my exams i.e. after 20 dec

**Comment by 0xPrateek** [comment]
No worries..! Best of luck for your Exams

**Pull request merged**
